### ISSUE TITLE
Support maven parallel build

### ISSUE THREAD

**Issue by ceilfors** [Ozsie/detekt-maven-plugin#34]
Maven supports the concept of [parallel build](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3). This can be enabled by running Maven in this manner:

```
./mvnw detekt:check -T 4
```

Unfortunately `detekt-maven-plugin` will throw the following error when Maven parallel build is enabled. This is the error message that will be generated:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.693 s (Wall Clock)
[INFO] Finished at: 2019-12-11T17:22:06+00:00
[INFO] Final Memory: 41M/517M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check (default-cli) on project A: Execution default-cli of goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check failed: Duplicate registration for EP: org.jetbrains.kotlin.com.intellij.treeCopyHandler: original plugin null, new plugin null -> [Help 1]
[ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check (default-cli) on project B: Execution default-cli of goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check failed: Duplicate registration for EP: org.jetbrains.kotlin.com.intellij.treeCopyHandler: original plugin null, new plugin null -> [Help 1]
[ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check (default-cli) on project C: Execution default-cli of goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check failed: Duplicate registration for EP: org.jetbrains.kotlin.com.intellij.treeCopyHandler: original plugin null, new plugin null -> [Help 1]
[ERROR]
```

This is the stacktrace of the error when Maven debug (-X) is enabled:

```
[ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check (default) on project A-project: Execution default of goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check failed: Duplicate registration for EP: org.jetbrains.kotlin.com.intellij.treeCopyHandler: original plugin null, new plugin null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check (default) on project A-project: Execution default of goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check failed: Duplicate registration for EP: org.jetbrains.kotlin.com.intellij.treeCopyHandler: original plugin null, new plugin null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.ozsie:detekt-maven-plugin:1.0.0-RC16:check failed: Duplicate registration for EP: org.jetbrains.kotlin.com.intellij.treeCopyHandler: original plugin null, new plugin null
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 11 more
Caused by: org.jetbrains.kotlin.com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: Duplicate registration for EP: org.jetbrains.kotlin.com.intellij.treeCopyHandler: original plugin null, new plugin null
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.checkThatPointNotDuplicated(ExtensionsAreaImpl.java:284)
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.registerExtensionPoint(ExtensionsAreaImpl.java:289)
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.doRegisterExtensionPoint(ExtensionsAreaImpl.java:265)
	at org.jetbrains.kotlin.com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.registerExtensionPoint(ExtensionsAreaImpl.java:238)
	at io.gitlab.arturbosch.detekt.api.internal.DetektPomModel.<init>(DetektPomModel.kt:26)
	at io.gitlab.arturbosch.detekt.api.internal.KotlinEnvironmentUtilsKt.createKotlinCoreEnvironment(KotlinEnvironmentUtils.kt:38)
	at io.gitlab.arturbosch.detekt.core.ProcessingSettings$environment$2.invoke(ProcessingSettings.kt:86)
	at io.gitlab.arturbosch.detekt.core.ProcessingSettings$environment$2.invoke(ProcessingSettings.kt:23)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.gitlab.arturbosch.detekt.core.ProcessingSettings.getEnvironment(ProcessingSettings.kt)
	at io.gitlab.arturbosch.detekt.core.DetektFacade.<init>(DetektFacade.kt:34)
	at io.gitlab.arturbosch.detekt.core.DetektFacade$Companion.create(DetektFacade.kt:112)
	at io.gitlab.arturbosch.detekt.core.DetektFacade$Companion.create(DetektFacade.kt:96)
	at io.gitlab.arturbosch.detekt.cli.runners.Runner.execute(Runner.kt:23)
	at com.github.ozsie.CheckMojo.execute(CheckMojo.kt:26)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 12 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
```

**Comment by Ozsie** [comment]
I'm guessing I will have to wait until https://github.com/arturbosch/detekt/issues/2433 is solved.

**Comment by arturbosch** [comment]
Please try out version 1.7.0 and verify if this is now fixed for you.

**Comment by Ozsie** [comment]
Version 1.7.0 has been released and should be available from Maven Central soon, can you try again to see if the update helped?

**Comment by pinkasey** [comment]
I've tried it with detekt 1.7.0
Build succeeded, but I got this warning:
```
[INFO] --------------------------------[ pom ]---------------------------------
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in Backend Services:
[WARNING] com.github.ozsie:detekt-maven-plugin:1.7.0
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```
